# Generated by Django 3.0.8 on 2020-08-21 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('name', models.CharField(max_length=32, verbose_name='名字')),
                ('sex', models.CharField(blank=True, max_length=32, verbose_name='性别')),
                ('department', models.CharField(blank=True, max_length=32, verbose_name='部门')),
                ('email', models.CharField(blank=True, max_length=32, verbose_name='邮箱')),
                ('remark', models.CharField(blank=True, default=0.0, max_length=32, verbose_name='评分')),
            ],
        ),
    ]
