# Generated by Django 3.0.8 on 2020-09-01 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tih_app', '0003_auto_20200831_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='burnin_result',
            name='timestamp',
            field=models.CharField(max_length=64, verbose_name='时间戳'),
        ),
    ]
